Fix error script bash on Windows 'MINGW'
	error message :
		Error: Could not find or load main class Main
		Caused by: java.lang.ClassNotFoundException: Main

	Sources : https://stackoverflow.com/questions/219585/including-all-te-jars-in-a-direcory-wihin-the-jahttva-classpath