README.md and script bash
"javac Main" in README.md : error: Class names, 'Main', are only accepted if annotation processing is explicitly requested

"bash Generateur_ANFR.sh" :
Error: Could not find or load main class Main
Caused by: java.lang.ClassNotFoundException: Main